"Copyright © 2017 National Fire Protection Association®."
"Todos los derechos reservados."
"La presente edición  de NFPA 3, Norma para el Comisionamiento de Sistemas de Protección contra Incendios y Seguridad Humana, fue preparada por el Comité Técnico sobre Comisionamiento y Pruebas Integradas."
"Fue emitida por el Consejo de Normas el 1 de agosto de 2017, con fecha de entrada en vigor 21 de agosto de 2017 y reemplaza a todas las decisiones anteriores."
"Esta edición de NFPA 3 se aprobó como Norma Nacional de los Estados Unidos el 21 de agosto de 2017."